In [29]:
import os

raw_path = "/content/drive/MyDrive/Scientific Project 2026/SP500_Project_Data/data/raw"

os.makedirs(raw_path, exist_ok=True)

print("Raw folder created.")
print(os.listdir(
    "/content/drive/MyDrive/Scientific Project 2026/SP500_Project_Data/data"
))
from google.colab import files

uploaded = files.upload()
import shutil

shutil.move(
    "sp500_raw.csv",
    "/content/drive/MyDrive/Scientific Project 2026/SP500_Project_Data/data/raw/sp500_raw.csv"
)

print("File moved successfully.")

Raw folder created.
['processed', 'raw']

Saving sp500_raw.csv to sp500_raw (1).csv
File moved successfully.

In [30]:
import os

raw_path = "/content/drive/MyDrive/Scientific Project 2026/SP500_Project_Data/data/raw"

print(os.listdir(raw_path))

['sp500_raw.csv']

In [31]:
df = pd.read_csv(
    "/content/drive/MyDrive/Scientific Project 2026/SP500_Project_Data/data/raw/sp500_raw.csv",
    index_col=0,
    parse_dates=True
)

display(df.head())

                   Open         High          Low        Close      Volume
Date
2000-01-03  1469.250000  1478.000000  1438.359985  1455.219971   931800000
2000-01-04  1455.219971  1455.219971  1397.430054  1399.420044  1009000000
2000-01-05  1399.420044  1413.270020  1377.680054  1402.109985  1085500000
2000-01-06  1402.109985  1411.900024  1392.099976  1403.449951  1092300000
2000-01-07  1403.449951  1441.469971  1400.729980  1441.469971  1225200000

In [32]:
# import libraries
import os   #use it mainly for handling file paths
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# define file path
# Your shared Google Drive project folder
project_dir = "/content/drive/MyDrive/Scientific Project 2026/SP500_Project_Data"

# Location of the raw dataset created in Notebook 01
raw_data_path = os.path.join(
    project_dir,
    "data",
    "raw",
    "sp500_raw.csv"
)

# Location where the processed dataset will be saved
processed_data_dir = os.path.join(
    project_dir,
    "data",
    "processed"
)

# Create the processed folder if it does not exist
os.makedirs(processed_data_dir, exist_ok=True)

processed_data_path = os.path.join(
    processed_data_dir,
    "processed_returns.csv"
)

# Check that the raw dataset exists
print("Checking raw dataset location...")

print("Raw file path:")
print(raw_data_path)

print("\nFile exists:", os.path.exists(raw_data_path))

# Load the raw S&P 500 datasets
print("\nLoading raw S&P 500 dataset...")

df = pd.read_csv(
    raw_data_path,
    index_col=0,
    parse_dates=True
)

print("Dataset loaded successfully!")

# Verify that the dataset has been imported correctly
print("\nFirst five observations:")
display(df.head())    # Shows the first five rows for inspection

print("\nDataset information:")
df.info()   # Displays information about the dataset

print("\nMissing values:")
print(df.isnull().sum())    # Checks for missing values in every column: If every column is zero, there are no missing values.

#fill missing values
df = df.bfill()   #Backfills missing values using the next available observation
df = df.ffill()   #Forward fills any remaining missing values using the previous observation.
print("\nMissing values after filling:")
print(df.isnull().sum())

# Calculate daily log return based on the closing price.
# Multiplication by 100 expresses the return as a percentage.

#calculate log returns
#Creates a new column called LogReturn.
df["LogReturn"] = (
    np.log(df["Close"] / df["Close"].shift(1))
) * 100

# The first observation has no previous closing price,
# so its log return is undefined and is removed.
df = df.dropna(subset=["LogReturn"])

# Save the processed dataset
df.to_csv(processed_data_path)

print("\n" + "-" * 60)
print("Data processing completed successfully!")
print(f"Processed dataset saved to:\n{processed_data_path}")
print("-" * 60)

# Display the processed dataset
print(f"\nTotal observations: {len(df)}")

display(df.head())

print("\nProcessed dataset information:")
df.info()

Checking raw dataset location...
Raw file path:
/content/drive/MyDrive/Scientific Project 2026/SP500_Project_Data/data/raw/sp500_raw.csv

File exists: True

Loading raw S&P 500 dataset...
Dataset loaded successfully!

First five observations:

                   Open         High          Low        Close      Volume
Date
2000-01-03  1469.250000  1478.000000  1438.359985  1455.219971   931800000
2000-01-04  1455.219971  1455.219971  1397.430054  1399.420044  1009000000
2000-01-05  1399.420044  1413.270020  1377.680054  1402.109985  1085500000
2000-01-06  1402.109985  1411.900024  1392.099976  1403.449951  1092300000
2000-01-07  1403.449951  1441.469971  1400.729980  1441.469971  1225200000

Dataset information:
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6684 entries, 2000-01-03 to 2026-07-31
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    6684 non-null   float64
 1   High    6684 non-null   float64
 2   Low     6684 non-null   float64
 3   Close   6684 non-null   float64
 4   Volume  6684 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 313.3 KB

Missing values:
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

Missing values after filling:
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

------------------------------------------------------------
Data processing completed successfully!
Processed dataset saved to:
/content/drive/MyDrive/Scientific Project 2026/SP500_Project_Data/data/processed/processed_returns.csv
------------------------------------------------------------

Total observations: 6683

,Open,High,Low,Close,Volume,LogReturn
Date,,,,,,
2000-01-04,1455.219971,1455.219971,1397.430054,1399.420044,1009000000,-3.909918
2000-01-05,1399.420044,1413.270020,1377.680054,1402.109985,1085500000,0.192034
2000-01-06,1402.109985,1411.900024,1392.099976,1403.449951,1092300000,0.095522
2000-01-07,1403.449951,1441.469971,1400.729980,1441.469971,1225200000,2.672995
2000-01-10,1441.469971,1464.359985,1441.469971,1457.599976,1064800000,1.112782

Processed dataset information:
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6683 entries, 2000-01-04 to 2026-07-31
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       6683 non-null   float64
 1   High       6683 non-null   float64
 2   Low        6683 non-null   float64
 3   Close      6683 non-null   float64
 4   Volume     6683 non-null   int64
 5   LogReturn  6683 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 365.5 KB