<a href="https://colab.research.google.com/github/fleurclochette/Scientific-Project-SS26/blob/main/notebooks/02b_preprocessing_extended.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%cd /content

/content

In [2]:
from getpass import getpass

github_token = getpass("Enter your GitHub Token: ")
github_username = input("Enter your GitHub username: ")

Enter your GitHub Token: ··········
Enter your GitHub username: fleurclochette

In [3]:
!git clone https://{github_username}:{github_token}@github.com/fleurclochette/Scientific-Project-SS26.git /content/Scientific-Project-SS26

Cloning into '/content/Scientific-Project-SS26'...
remote: Enumerating objects: 338, done.
remote: Counting objects: 100% (185/185), done.
remote: Compressing objects: 100% (153/153), done.
Receiving objects: 100% (338/338), 1.55 MiB | 8.03 MiB/s, done.
remote: Total 338 (delta 107), reused 57 (delta 30), pack-reused 153 (from 1)
Resolving deltas: 100% (164/164), done.

In [4]:
# Connect to repository
%cd /content/Scientific-Project-SS26

!git pull

/content/Scientific-Project-SS26
Already up to date.

In [5]:
# import libraries
import os   #use it mainly for handling file paths
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
# Define the GitHub repository directory
project_dir = "/content/Scientific-Project-SS26"

# Location of the extended raw S&P 500 dataset
raw_data_path = os.path.join(
    project_dir,
    "data",
    "raw",
    "sp500_1970_raw.csv"
)

# Location where the processed dataset will be saved
processed_data_dir = os.path.join(
    project_dir,
    "data",
    "processed"
)

# Create processed folder if it does not exist
os.makedirs(
    processed_data_dir,
    exist_ok=True
)

# Full path for the processed dataset
processed_data_path = os.path.join(
    processed_data_dir,
    "processed_returns_1970.csv"
)

In [7]:
# Check the raw dataset
print("Checking raw dataset location...")

print("Raw file path:")
print(raw_data_path)

print("\nFile exists:")
print(os.path.exists(raw_data_path))

Checking raw dataset location...
Raw file path:
/content/Scientific-Project-SS26/data/raw/sp500_1970_raw.csv

File exists:
True

In [8]:
# Load the raw S&P 500 datasets
print("\nLoading raw S&P 500 dataset...")

df = pd.read_csv(
    raw_data_path,
    parse_dates=["Date"]
)

print("Dataset loaded successfully!")

print("\nColumns:")
print(df.columns)

print("\nFirst five observations:")
display(df.head())

print(df["Date"].dtype)
print(df["Date"].min())
print(df["Date"].max())
df = df.sort_values("Date").reset_index(drop=True)

Loading raw S&P 500 dataset...
Dataset loaded successfully!

Columns:
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

First five observations:

        Date       Open       High        Low      Close    Volume
0 1970-01-02  92.059998  93.540001  91.790001  93.000000   8050000
1 1970-01-05  93.000000  94.250000  92.529999  93.459999  11490000
2 1970-01-06  93.459999  93.809998  92.129997  92.820000  11460000
3 1970-01-07  92.820000  93.379997  91.930000  92.629997  10010000
4 1970-01-08  92.629997  93.470001  91.989998  92.680000  10670000

datetime64[ns]
1970-01-02 00:00:00
2026-08-28 00:00:00

In [9]:
# Inspect the data
print("\nDataset information:")
df.info()

print("\nMissing values:")
print(df.isnull().sum())

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14286 entries, 0 to 14285
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    14286 non-null  datetime64[ns]
 1   Open    14286 non-null  float64
 2   High    14286 non-null  float64
 3   Low     14286 non-null  float64
 4   Close   14286 non-null  float64
 5   Volume  14286 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 669.8 KB

Missing values:
Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [10]:
# Missing Values
df = df.bfill()
df = df.ffill()

print("\nMissing values after filling:")
print(df.isnull().sum())

Missing values after filling:
Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [11]:
# Calculating log returns
df["LogReturn"] = (
    np.log(
        df["Close"] / df["Close"].shift(1)
    )
) * 100
# The first observation has no previous closing price,
# so its log return is undefined and is removed.
df = df.dropna(
    subset=["LogReturn"]
)

In [12]:
# Save the processed dataset
df.to_csv(
    processed_data_path,
    index=False
)

print("\n" + "-" * 60)
print("Data processing completed successfully!")
print(
    f"Processed dataset saved to:\n"
    f"{processed_data_path}"
)
print("-" * 60)

------------------------------------------------------------
Data processing completed successfully!
Processed dataset saved to:
/content/Scientific-Project-SS26/data/processed/processed_returns_1970.csv
------------------------------------------------------------

In [13]:
# Verification
print(f"\nTotal observations: {len(df)}")

display(df.head())

print("\nProcessed dataset information:")
df.info()

print(
    "\nProcessed file exists:",
    os.path.exists(processed_data_path)
)

Total observations: 14285

        Date       Open       High        Low      Close    Volume  LogReturn
1 1970-01-05  93.000000  94.250000  92.529999  93.459999  11490000   0.493403
2 1970-01-06  93.459999  93.809998  92.129997  92.820000  11460000  -0.687140
3 1970-01-07  92.820000  93.379997  91.930000  92.629997  10010000  -0.204910
4 1970-01-08  92.629997  93.470001  91.989998  92.680000  10670000   0.053967
5 1970-01-09  92.680000  93.250000  91.820000  92.400002   9380000  -0.302571

Processed dataset information:
<class 'pandas.core.frame.DataFrame'>
Index: 14285 entries, 1 to 14285
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       14285 non-null  datetime64[ns]
 1   Open       14285 non-null  float64
 2   High       14285 non-null  float64
 3   Low        14285 non-null  float64
 4   Close      14285 non-null  float64
 5   Volume     14285 non-null  int64
 6   LogReturn  14285 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 892.8 KB

Processed file exists: True

In [25]:
%cd /content/Scientific-Project-SS26
!git status

/content/Scientific-Project-SS26
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	data/processed/processed_returns_1970.csv

nothing added to commit but untracked files present (use "git add" to track)

In [26]:
!git add data/processed/processed_returns_1970.csv

In [27]:
!git add notebooks/02b_preprocessing_extended.ipynb

In [28]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   data/processed/processed_returns_1970.csv

In [33]:
!git commit -m "Add extended S&P 500 preprocessing and processed data"

[main abf2198] Add extended S&P 500 preprocessing and processed data

In [35]:
!git pull --no-rebase origin main

From https://github.com/fleurclochette/Scientific-Project-SS26
 * branch            main       -> FETCH_HEAD
Already up to date.

In [36]:
!git push origin main

Enumerating objects: 13, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 2 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 418.15 KiB | 4.14 MiB/s, done.
Total 7 (delta 3), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (3/3), completed with 2 local objects.
To https://github.com/fleurclochette/Scientific-Project-SS26.git
   bb84414..abf2198  main -> main

In [37]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean