In [59]:
%cd /content

/content

In [60]:
from getpass import getpass

github_token = getpass("Enter your GitHub Token: ")
github_username = input("Enter your GitHub username: ")

Enter your GitHub Token: ··········
Enter your GitHub username: fleurclochette

In [61]:
!git clone https://{github_username}:{github_token}@github.com/fleurclochette/Scientific-Project-SS26.git /content/Scientific-Project-SS26

/bin/bash: -c: line 1: syntax error near unexpected token `('
/bin/bash: -c: line 1: `git clone https://fleurclochette:df = pd.read_csv(     raw_data_path,     parse_dates=["Date"] )@github.com/fleurclochette/Scientific-Project-SS26.git /content/Scientific-Project-SS26'

In [62]:
# Connect to repository
%cd /content/Scientific-Project-SS26

!git pull

/content/Scientific-Project-SS26
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 0 (delta 0), pack-reused 0 (from 0)
Unpacking objects: 100% (4/4), 1.77 KiB | 602.00 KiB/s, done.
From https://github.com/fleurclochette/Scientific-Project-SS26
   0f10964..c95cae3  main       -> origin/main
Updating 0f10964..c95cae3
Fast-forward
 notebooks/02_preprocessing.ipynb | 257 +++++++++++++++++++++++++++++++++++----
 1 file changed, 236 insertions(+), 21 deletions(-)

In [63]:
# import libraries
import os   #use it mainly for handling file paths
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [64]:
# Define the GitHub repository directory
project_dir = "/content/Scientific-Project-SS26"

# Location of the raw dataset created in Notebook 01
raw_data_path = os.path.join(
    project_dir,
    "data",
    "raw",
    "sp500_raw.csv"
)

# Location where the processed dataset will be saved
processed_data_dir = os.path.join(
    project_dir,
    "data",
    "processed"
)

# Create processed folder if it does not exist
os.makedirs(
    processed_data_dir,
    exist_ok=True
)

# Full path for the processed dataset
processed_data_path = os.path.join(
    processed_data_dir,
    "processed_returns.csv"
)

In [65]:
# Check the raw dataset
print("Checking raw dataset location...")

print("Raw file path:")
print(raw_data_path)

print("\nFile exists:")
print(os.path.exists(raw_data_path))

Checking raw dataset location...
Raw file path:
/content/Scientific-Project-SS26/data/raw/sp500_raw.csv

File exists:
True

In [66]:
# Load the raw S&P 500 datasets
print("\nLoading raw S&P 500 dataset...")

df = pd.read_csv(
    raw_data_path,
    parse_dates=["Date"]
)

print("Dataset loaded successfully!")

print("\nColumns:")
print(df.columns)

print("\nFirst five observations:")
display(df.head())

print(df["Date"].dtype)
print(df["Date"].min())
print(df["Date"].max())
df = df.sort_values("Date").reset_index(drop=True)

Loading raw S&P 500 dataset...
Dataset loaded successfully!

Columns:
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

First five observations:

        Date         Open         High          Low        Close      Volume
0 2000-01-03  1469.250000  1478.000000  1438.359985  1455.219971   931800000
1 2000-01-04  1455.219971  1455.219971  1397.430054  1399.420044  1009000000
2 2000-01-05  1399.420044  1413.270020  1377.680054  1402.109985  1085500000
3 2000-01-06  1402.109985  1411.900024  1392.099976  1403.449951  1092300000
4 2000-01-07  1403.449951  1441.469971  1400.729980  1441.469971  1225200000

datetime64[ns]
2000-01-03 00:00:00
2026-07-31 00:00:00

In [67]:
# Inspect the data
print("\nDataset information:")
df.info()

print("\nMissing values:")
print(df.isnull().sum())

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6684 entries, 0 to 6683
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    6684 non-null   datetime64[ns]
 1   Open    6684 non-null   float64
 2   High    6684 non-null   float64
 3   Low     6684 non-null   float64
 4   Close   6684 non-null   float64
 5   Volume  6684 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 313.4 KB

Missing values:
Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [68]:
# Missing Values
df = df.bfill()
df = df.ffill()

print("\nMissing values after filling:")
print(df.isnull().sum())

Missing values after filling:
Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [69]:
# Calculating log returns
df["LogReturn"] = (
    np.log(
        df["Close"] / df["Close"].shift(1)
    )
) * 100
# The first observation has no previous closing price,
# so its log return is undefined and is removed.
df = df.dropna(
    subset=["LogReturn"]
)

In [70]:
# Save the processed dataset
df.to_csv(
    processed_data_path,
    index=False
)

print("\n" + "-" * 60)
print("Data processing completed successfully!")
print(
    f"Processed dataset saved to:\n"
    f"{processed_data_path}"
)
print("-" * 60)

------------------------------------------------------------
Data processing completed successfully!
Processed dataset saved to:
/content/Scientific-Project-SS26/data/processed/processed_returns.csv
------------------------------------------------------------

In [71]:
# Verification
print(f"\nTotal observations: {len(df)}")

display(df.head())

print("\nProcessed dataset information:")
df.info()

print(
    "\nProcessed file exists:",
    os.path.exists(processed_data_path)
)

Total observations: 6683

,Date,Open,High,Low,Close,Volume,LogReturn
1,2000-01-04,1455.219971,1455.219971,1397.430054,1399.420044,1009000000,-3.909918
2,2000-01-05,1399.420044,1413.270020,1377.680054,1402.109985,1085500000,0.192034
3,2000-01-06,1402.109985,1411.900024,1392.099976,1403.449951,1092300000,0.095522
4,2000-01-07,1403.449951,1441.469971,1400.729980,1441.469971,1225200000,2.672995
5,2000-01-10,1441.469971,1464.359985,1441.469971,1457.599976,1064800000,1.112782

Processed dataset information:
<class 'pandas.core.frame.DataFrame'>
Index: 6683 entries, 1 to 6683
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       6683 non-null   datetime64[ns]
 1   Open       6683 non-null   float64
 2   High       6683 non-null   float64
 3   Low        6683 non-null   float64
 4   Close      6683 non-null   float64
 5   Volume     6683 non-null   int64
 6   LogReturn  6683 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 417.7 KB

Processed file exists: True

In [72]:
%cd /content/Scientific-Project-SS26
!git status

/content/Scientific-Project-SS26
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   data/processed/processed_returns.csv

no changes added to commit (use "git add" and/or "git commit -a")

In [73]:
!git add data/processed/processed_returns.csv

In [74]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   data/processed/processed_returns.csv

In [75]:
!git config --global user.name "fleurclochette"
!git config --global user.email "fleur.clochette.221@gmail.com"

In [76]:
!git commit -m "Add processed S&P 500 returns data"

[main d555b72] Add processed S&P 500 returns data
 1 file changed, 6684 insertions(+), 6684 deletions(-)
 rewrite data/processed/processed_returns.csv (89%)

In [77]:
!git commit -m "Merge remote changes with preprocessing updates"

On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean

In [78]:
!git push origin main

Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 2 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 46.24 KiB | 1.22 MiB/s, done.
Total 5 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To https://github.com/fleurclochette/Scientific-Project-SS26.git
   c95cae3..d555b72  main -> main

In [79]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [80]:
!git commit -m "Merge remote changes with preprocessing updates"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [81]:
raw_check = pd.read_csv(raw_data_path)

print("Columns in raw CSV:")
print(raw_check.columns)

print("\nFirst 5 rows:")
display(raw_check.head())

Columns in raw CSV:
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

First 5 rows:

         Date         Open         High          Low        Close      Volume
0  2000-01-03  1469.250000  1478.000000  1438.359985  1455.219971   931800000
1  2000-01-04  1455.219971  1455.219971  1397.430054  1399.420044  1009000000
2  2000-01-05  1399.420044  1413.270020  1377.680054  1402.109985  1085500000
3  2000-01-06  1402.109985  1411.900024  1392.099976  1403.449951  1092300000
4  2000-01-07  1403.449951  1441.469971  1400.729980  1441.469971  1225200000

In [82]:
print("Index:")
print(raw_check.index)

print("\nIndex name:")
print(raw_check.index.name)
print("\nFirst column values:")
print(raw_check.iloc[:, 0].head())

Index:
RangeIndex(start=0, stop=6684, step=1)

Index name:
None

First column values:
0    2000-01-03
1    2000-01-04
2    2000-01-05
3    2000-01-06
4    2000-01-07
Name: Date, dtype: object